### ISSUE TITLE
[GENERAL] Hunger seems to be draining excessively quickly

### ISSUE THREAD

**Issue by IgnusVam** [Willburd/CHOMPost21#76] opened 2024-06-15 05:58 UTC
#### Brief description of the bug

Crew seem to be getting hungry significantly faster than before, which becomes suffering on teshari players.
I suspect this was changed because of Virgo players eating 20+ players with save weight on, then wondering why they become rolling blobs that never lose weight.

**Comment by Willburd** [comment] 2024-06-25 10:57
Confirmed to be due to reagent generation in belly, won't fix.

**Closed by Willburd** 2024-06-25 10:57 UTC
Labels: wontfix
